# Generated by Django 4.2 on 2024-02-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
